version: "3.9"

services:
  mariadb:
    image: mariadb:11.0
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "rootpass"
      MARIADB_USER: "cruduser"
      MARIADB_PASSWORD: "crudpass"
      MARIADB_DATABASE: "cruddemo"
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build: .
    depends_on:
      - mariadb
    environment:
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_DB: cruddemo
      MARIADB_USER: cruduser
      MARIADB_PASSWORD: crudpass
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
  
  fluentbit:
    image: fluent/fluent-bit:2.1
    volumes:
      - ./app.log:/app/app.log
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf

    environment:
      - LOKI_HOST=${LOKI_HOST}
      - LOKI_JOB=${LOKI_JOB}
    depends_on:
      - api

volumes:
  mariadb_data:
